version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=BYTUBE;Username=admin;Password=root
    depends_on:
      - postgresdb

    # Настройки для авто-определения URL для запуска
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp-http.rule=Host(`localhost`)"
      - "traefik.http.services.webapp.loadbalancer.server.port=8080"
      - "traefik.http.routers.webapp-https.rule=Host(`localhost`)"
      - "traefik.http.routers.webapp-https.tls=true"
      - "traefik.http.services.webapp-https.loadbalancer.server.port=8081"

  postgresdb:
    image: postgres:15
    environment:
      POSTGRES_DB: BYTUBE
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: