// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BYTUBE.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20241122192912_initState")]
    partial class initState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BYTUBE.Entity.Models.Channel", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("Id");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Comment", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<int>>("Likes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("VideoGuid")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("Id");

                    b.HasIndex("VideoGuid");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Playlist", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<int>("Access")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("Id");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.PlaylistItem", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("integer");

                    b.Property<int>("VideoGuid")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("VideoGuid");

                    b.ToTable("PlaylistItems");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Report", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("VideoGuid")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("VideoGuid");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Subscribe", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("ChannelId");

                    b.HasIndex("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.User", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("LikedVideo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Video", b =>
                {
                    b.Property<int>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Guid"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<List<int>>("Dislikes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<int>>("Likes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoAccess")
                        .HasColumnType("int");

                    b.Property<int>("VideoStatus")
                        .HasColumnType("int");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("OwnerId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Channel", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.User", "Owner")
                        .WithMany("Channels")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Comment", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYTUBE.Entity.Models.Video", "Video")
                        .WithMany("Comments")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Playlist", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.PlaylistItem", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.Playlist", "Playlist")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYTUBE.Entity.Models.Video", "Video")
                        .WithMany("PlaylistItems")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Report", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.Video", "Video")
                        .WithMany("Reports")
                        .HasForeignKey("VideoGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Subscribe", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.Channel", "Channel")
                        .WithMany("Subscribes")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BYTUBE.Entity.Models.User", "User")
                        .WithMany("Subscribes")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Video", b =>
                {
                    b.HasOne("BYTUBE.Entity.Models.Channel", "Owner")
                        .WithMany("Videos")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Channel", b =>
                {
                    b.Navigation("Subscribes");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistItems");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.User", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Comments");

                    b.Navigation("Playlists");

                    b.Navigation("Subscribes");
                });

            modelBuilder.Entity("BYTUBE.Entity.Models.Video", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PlaylistItems");

                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
